apiVersion: v1
kind: Service
metadata:
  name: geecache-storage
  labels:
    app: geecache-storage
spec:
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: rpc
  selector:
    app: geecache-storage
  type: ClusterIP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: geecache-storage
spec:
  serviceName: "geecache-storage"
  replicas: 1
  selector:
    matchLabels:
      app: geecache-storage
  template:
    metadata:
      labels:
        app: geecache-storage
    spec:
      containers:
      - name: storage-server
        image: geecache-storage:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
          name: rpc
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
